#!/bin/sh

cd $(dirname "$0")/..

# set osx config
yes | source "$(pwd)/osx/init.sh"

# install homebrew if it does not exist
if [ ! -x /usr/local/bin/brew ]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew bundle

# checkout git submodules
git submodule init
git submodule update

# bash
ln -nfs "$(pwd)/bash/profile.sh" ~/.bash_profile
ln -nfs "$(pwd)/bash/inputrc.sh" ~/.inputrc

# git
ln -nfs "$(pwd)/git/gitconfig" ~/.gitconfig

# vim
ln -nfs "$(pwd)/vim/.vim" ~/.vim
ln -nfs "$(pwd)/vim/vimrc" ~/.vimrc
ln -nfs "$(pwd)/vim/gvimrc" ~/.gvimrc
vim +PluginInstall +qall
