#!/bin/sh

# set args
while :; do
  case $1 in
    -v) VERBOSE_MODE=true
    ;;
    -v) SKIP_GIT=true
    ;;
    -v) SKIP_VIM=true
    ;;
    -v) SKIP_ZSH=true
    ;;
    *) break
  esac
  shift
done

echo_warning () {
  echo "$(tput setaf 3)$1$(tput sgr 0)"
}

remove_dotfiles_symlink () {
  # check if the file exists
  if [ ! -e $1 ]; then
    if [ "$VERBOSE_MODE" == true ]; then
      echo "Could not remove $1 because it doesn’t exist."
    fi
    return
  fi

  # check if the file is a symlink
  if [ -L $1 ]; then
    rm $1
  else
    if [ "$VERBOSE_MODE" == true ]; then
      echo "Could not remove $1 because it is not a symlink."
    fi
  fi
}

if [ "$SKIP_ZSH" == true ]; then
  echo_warning "Skipping zsh..."
else
  remove_dotfiles_symlink ~/.zsh_config
  uninstall_oh_my_zsh
fi

if [ "$SKIP_GIT" == true ]; then
  echo_warning "Skipping git..."
else
  remove_dotfiles_symlink ~/.gitignore_global
fi

if [ "$SKIP_VIM" == true ]; then
  echo_warning "Skipping vim..."
else
  remove_dotfiles_symlink ~/.vim
  remove_dotfiles_symlink ~/.vimrc
  remove_dotfiles_symlink ~/.gvimrc
fi
